INSERT INTO states VALUES ('BIHAR','INDIA');

INSERT INTO states VALUES ('DELHI','INDIA');

INSERT INTO states VALUES ('ALBERTA','CANADA');

INSERT INTO states VALUES ('VICTORIA','AUSTRALIA');

INSERT INTO states VALUES ('QUEENSLAND','AUSTRALIA');

COMMIT;

SELECT * FROM states;